### ISSUE TITLE
Added new user, but they have no ingredients

### ISSUE THREAD

**Issue by withanhdammit** [nazgul26/PHPRecipebook#32]
I added a new user, but when that user goes to add a new recipe there are no ingredients listed.
<img width="1116" alt="screen shot 2016-01-14 at 6 51 44 am" src="https://cloud.githubusercontent.com/assets/16404870/12327427/4efecb00-ba8b-11e5-872f-766827b79527.png">

**Comment by nazgul26** [comment]
Was the option checked to 'Create with default ingredients' and does the 'admin' (user - 0) have ingredients?  The magic to have default ingredients is to copy from the Admin/default user as a starting point.  This gives the option to setup what ingredients your users will get.  Let me know if my assumptions are not correct and if there is something else going on you can point me towards.

**Comment by withanhdammit** [comment]
Interesting, the Admin user does not have any ingredients.  

I did create the new user with the default ingredients checked, but no
ingredients.  Is that because the default user ‘0’ doesn’t have any
ingredients?  And why does each user need their own ingredients, if we’re
not using “core_ingredients” then IMHO it should just be a list of
ingredients that everyone can use.  Would save a lot of space, especially if
you had a bunch of users.

Attached my ingredients.sql table.

**Comment by nazgul26** [comment]
Insert the default ingredients for the admin user.  In the setup wizard it is this step:

Import sample ingredients (optional) -
Config/SQL/sample_ingredients.sql(optional) 

That will get your admin user setup with ingredients and then give a place to copy to each additional user.

core ingredients has been remove, since like you said it is really not used. It was going to be for USDA reference to ingredients.  Didn't go anywhere with that so I have removed it.

If I had a master list of ingredients then multi-user systems would have to have a single list to maintain which is not ideal (extra work for an 'admin').    Users using the system as a single user setup also are not hurt since they  just use the 'admin' list of ingredients.  

A perfect setup would be a merge of ingredients from a master list with mods hanging off for users, but that is not in scope for what I am going to write.  If someone wants to make the brilliant mod I would be interested to see it.
