### ISSUE TITLE
Request: Update schema with EAN

### ISSUE THREAD

**Issue by KHome** [nazgul26/PHPRecipebook#47]
Hi,

I would like to add an Barcode (EAN) to the Database schema.
My vision is following...

a) Add to shopping list:
Use Barcode Scanner to get an EAN from a "empty" ingredient.
Put this ingredient (identified by a comparison to the previously updated database) to the shopping list

b) Add a recipe to the meal planner:
Use a prepared "Hand-out" with favourite recipes picture -> scan custom-EAN to generate the meal plan.

I bought a cheap Bardcode-scanner, which sends the detected EAN to a python script.
Now I need a good idea to update a) Shopping list and b) Meal planner via python...
Any suggesting s ?

**Comment by nazgul26** [comment]
Probably the best way is to communicate with http/https between python and php.    The problem is you will need to login first and via python and that will be difficult.  If the recipes app was running on the same machine as the barcode script then you could insert directly to the db.  Lots of technical issues to solve for sure on this.

**Comment by nazgul26** [comment]
Beyond the scope of what I can do right now.  Maybe some new library/tech will come along and make this easier in the future. Sorry.
