### ISSUE TITLE
database error when adding ingredients

### ISSUE THREAD

**Issue by taehwan-kim** [nazgul26/PHPRecipebook#54]
Hello, 

I am running the PHPRecipebook installed on heroku, and I get following error when i'm trying to add any ingredient in a recipe:

<img width="1222" alt="screen shot 2017-04-09 at 11 59 55 am" src="https://cloud.githubusercontent.com/assets/7378320/24840127/4e7d8352-1d1c-11e7-9bb1-6a5fdd95187e.png">

It appears that the demo site (which seems like that's also deployed via heroku) has exact same problem. Is there a bug regarding recipe addition in the latest release?

Thanks.

**Comment by nazgul26** [comment]
It maybe an issue with using PostgresSQL.  I will re-test that and see.

**Comment by ilveroluca** [comment]
I've seen this too, and I run with PostgreSQL.  Next time I see it I'll report the type of input that causes it.

**Comment by nazgul26** [comment]
This was caused by the PostgreSQL sequences not being update as sample ingredients got inserted. I have updated the cake seed to not set the IDs thus it will incremented as it goes.

For existing situations I think this should fix it:

ALTER SEQUENCE  ingredients_id_seq RESTART WITH 328;

Or some value greater then the # of ingredients currently in the ingredients table.
